"""schema inicial

Revision ID: df005fb6bbb8
Revises: 
Create Date: 2026-05-29 21:31:45.924742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df005fb6bbb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fipe_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_fipe', sa.String(length=20), nullable=True),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('ref_mes', sa.String(length=20), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fipe_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fipe_cache_codigo_fipe'), ['codigo_fipe'], unique=False)

    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('min_tier', sa.Integer(), nullable=False),
    sa.Column('rate_limit_s', sa.Float(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_slug'), ['slug'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_chave'), ['chave'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('criterios_json', sa.JSON(), nullable=False),
    sa.Column('frequencia_min', sa.Integer(), nullable=False),
    sa.Column('threshold_desconto', sa.Float(), nullable=False),
    sa.Column('canais_notif', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_exec_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('versao', sa.String(length=200), nullable=True),
    sa.Column('ano_fab', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('faixa_km', sa.String(length=20), nullable=True),
    sa.Column('cambio', sa.String(length=30), nullable=True),
    sa.Column('combustivel', sa.String(length=30), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('grupo_chave', sa.String(length=300), nullable=True),
    sa.Column('hash_dedup', sa.String(length=64), nullable=False),
    sa.Column('fipe_codigo', sa.String(length=20), nullable=True),
    sa.Column('fipe_valor', sa.Integer(), nullable=True),
    sa.Column('primeiro_visto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_visto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_dedup', name='uq_listing_hash')
    )
    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_listings_ano_modelo'), ['ano_modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_grupo_chave'), ['grupo_chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_hash_dedup'), ['hash_dedup'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_modelo'), ['modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_listings_preco'), ['preco'], unique=False)

    op.create_table('listing_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('preco_ref', sa.Integer(), nullable=True),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('origem_score', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['vehicle_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_scores_desconto'), ['desconto'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_scores_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_scores_score'), ['score'], unique=False)

    op.create_table('monitor_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('posicao_ranking', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['vehicle_listings.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id', 'listing_id', name='uq_match_monitor_listing')
    )
    with op.batch_alter_table('monitor_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_matches_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_matches_monitor_id'), ['monitor_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['vehicle_listings.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_monitor_id'), ['monitor_id'], unique=False)

    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('tier_usado', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qtd_resultados', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_logs_portal_id'), ['portal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_portal_id'))

    op.drop_table('scrape_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_monitor_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('monitor_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_matches_monitor_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_matches_listing_id'))

    op.drop_table('monitor_matches')
    with op.batch_alter_table('listing_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_scores_score'))
        batch_op.drop_index(batch_op.f('ix_listing_scores_listing_id'))
        batch_op.drop_index(batch_op.f('ix_listing_scores_desconto'))

    op.drop_table('listing_scores')
    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_preco'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_portal_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_modelo'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_marca'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_hash_dedup'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_grupo_chave'))
        batch_op.drop_index(batch_op.f('ix_vehicle_listings_ano_modelo'))

    op.drop_table('vehicle_listings')
    op.drop_table('monitors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_chave'))

    op.drop_table('settings')
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_slug'))

    op.drop_table('portals')
    with op.batch_alter_table('fipe_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fipe_cache_codigo_fipe'))

    op.drop_table('fipe_cache')
    # ### end Alembic commands ###
